### ISSUE TITLE
Tela Saldo

### ISSUE THREAD

**Issue by gabriele-martins** [gabriele-martins/HackadevCSharks#2]
A tela de Saldo é onde o usuário poderá visualizar o saldo atual da sua conta bancária. Essa tela deve conter informações precisas e atualizadas, incluindo o saldo total e o saldo disponível para saque. O usuário também pode encontrar informações adicionais, como a data e hora da última transação realizada, bem como a taxa de juros aplicada em sua conta.

**Comment by marccosousa** [comment]
Test
